version: "2"

services:
  postgres-test:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: insapi-test
    volumes:
      - ./backups:/backups
      - ../postgresql-test:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres-test

  server:
    image: node:8.12.0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: insapi-test
      POSTGRES_HOST: postgres-test
    links:
      - postgres-test
      - maildev-test
    command: node_modules/mocha/bin/mocha test/mocha test/mocha/models/*.js

  maildev-test:
    image: djfarrelly/maildev
    ports:
      - 1081:80
